Fix #158
Try multiple locations for box.json.
If we cannot locate box.json, error out.

diff --git a/dist/Makefile b/dist/Makefile
--- a/dist/Makefile
+++ b/dist/Makefile
@@ -31,7 +31,9 @@ clean:
 
 sodium-compat.phar: dist/box.json composer.lock
 	if [ ! -d dist ]; then mkdir dist; fi
-	if [ ! -f dist/box.json ]; then cp ../dist/box.json dist/box.json; fi
+	if [ ! -f dist/box.json && -f ../box.json ]; then cp ../box.json dist/box.json; fi
+	if [ ! -f dist/box.json && -f ../dist/box.json ]; then cp ../dist/box.json dist/box.json; fi
+	if [ ! -f dist/box.json ]; then echo "Could not locate box.json" && exit 255; fi
 	cp dist/box.json .
 	php -d phar.readonly=0 $(box) build -c box.json -v
 
